from flask import Flask, render_template, request
import subprocess
from discord_webhook import DiscordWebhook, DiscordEmbed
import requests
app = Flask(__name__)

@app.route("/")
def home():
     client_ip = request.headers.get("X-Forwarded-For", request.remote_addr)
     return render_template("index.html", ip_address=client_ip)



def execute_command():
    command = request.form.get("command")

    output = subprocess.getoutput(command)
    send_discord_webhook(output)

    return output

def send_discord_webhook(message):
    webhook_url = "YOUR_DISCORD_WEBHOOK_URL"
    
    embed = DiscordEmbed(title="Webhook Notification", description=message, color=242424)
    embed.set_footer(text="Generated by Flask Server")
    
    webhook = DiscordWebhook(url=webhook_url)
    webhook.add_embed(embed)
    webhook.execute()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
